export type RequestType =
  'UPDATE' |
  'CREATE' |
  'SUM' |
  'FIRST_VALUE' |
  'COUNT' |
  'COPY' |
  'SEARCH' |
  'SEARCH_DROPDOWN' |
  'DELETE' |
  'EXTERNAL_API' |
  'AUTHENTICATION' |
  'PERMISSION' |
  'PERMISSION.GET_BY_AUTHORIZED_ID' |
  'PERMISSION.GET_ALL' |
  'PERMISSION.GET_ALL_FORM_PERMISSION' |
  'PERMISSION.INSERT' |
  'SETTING.FORM' |
  'SETTING.VIEW' |
  'SETTING.FILTER' |
  'SETTING.LAYOUT' |
  'SETTING.ADVANCED' |
  'SETTING.FEATURE' |
  'EXPORT.EXCEL' |
  'IMPORT_DATA' |
  'NESTEDSET.SYNC' |
  'GET_HOME' |
  'NESTEDSET.MOVE';
